name: bda
channels:
  - conda-forge
dependencies:
  - gdal<3.9
  - python<3.14
  - pip
  - pip:
    - adlfs
    - azure-storage-blob
    - dask_geopandas
    - deltalake
    - fiona
    - fsspec
    - geopandas
    - jupyter
    - mercantile
    - opencv-python
    - osmnx
    - pigeon-jupyter
    - planetary_computer
    - pyarrow
    - torch<2.11
    - rasterio
    - scikit-learn
    - tensorboard
    - torchgeo[all]
