name: bda
channels:
  - conda-forge
dependencies:
  - gdal
  - python<3.14
  - pip
  - pip:
    - adlfs
    - azure-storage-blob
    - dask_geopandas
    - deltalake
    - fsspec
    - geopandas
    - jupyter
    - mercantile
    - osmnx
    - pigeon-jupyter
    - planetary_computer
    - pyarrow
    - rasterio
    - rtree
    - scikit-learn
    - setuptools<81
    - tensorboard
    - torchgeo[all]
    - torch<2.11
