name: bda
channels:
  - conda-forge
dependencies:
  - gdal<3.9
  - python<3.11
  - pip
  - pip:
    - adlfs
    - azure-storage-blob
    - dask_geopandas
    - deltalake
    - geopandas
    - jupyter
    - mercantile
    - osmnx
    - pigeon-jupyter
    - planetary_computer
    - pyarrow
    - rasterio
    - s3fs
    - scikit-learn
    - tensorboard
    - torchgeo[all]
