experiment_name: "maui_demo_0"
experiment_dir: "experiments/maui_demo_0"

infrastructure:
  storage_account: "https://TODO.blob.core.windows.net/"  # REQUIRED -- URL of the Azure Blob Storage account
  container_name: TODO  # REQUIRED --name of the blob container in which to save experiment files
  sas_token: TODO  # REQUIRED --SAS token that has read/write access to the blob container in the format "sv=...."
  relative_path: "instance/"  # REQUIRED --relative path within blob container in which to save experiment files
  titiler_endpoint: "https://your.titiler.instance/"  # REQUIRED --path to a running TiTiler instance

imagery:
  raw_fn: "data/demo/raw/maxar_lahaina_8_12_2023-visual.tif"  # REQUIRED -- path to the raw imagery
  rgb_fn: "data/demo/raw/maxar_lahaina_8_12_2023-visual.tif"  # Optional, path to an RGB version of the raw imagery
  num_channels: 3  # REQUIRED -- Number of channels in the raw imagery (3 for RGB)
  normalization_means:  # REQUIRED -- Normalization values to use for each channel.
    - 0  # The imagery will be normalized as (x_c - mean_c) / std_c for each channel c.
    - 0  # The values here should be in the same order as the channels in the raw imagery.
    - 0  # E.g. if you have 8-bit imagery and you want to do [0,1] normalization, you can set means to 0 and stds to 255.
  normalization_stds:
    - 255
    - 255
    - 255

labels:
  fn: "data/demo/labels/Maui_Wildfires_August_0.geojson"  # Path to the label file that is generated by the satellite-imagery-labeling-tool
  classes:  # The unique values in the `class` column of the labels file.
    - Background  # Class value 1
    - Building  # Class value 2
    - Damaged Building  # Class value 3
  buffer_in_meters: 3  # Buffer this many meters around each `class_to_buffer` polygon with the `class_to_buffer_by` class value
  class_to_buffer: Building
  class_to_buffer_by: Background

training:
  learning_rate: 0.0001
  max_epochs: 40
  batch_size: 32
  gpu_id: 0
  log_dir: logs/
  checkpoint_subdir: checkpoints/
  use_constraint_loss: false

inference:
  output_subdir: "outputs/"
  checkpoint_fn: "checkpoints/last.ckpt"  # should mirror training.checkpoint_subdir
  batch_size: 2
  gpu_id: 1
  patch_size: 2048
  padding: 64
